// ============================================
// 📄 1. src/types/faq.types.ts
// ============================================

export interface FAQ {
  id: string;
  question: string;
  answer: string;
  category?: string;
  tags?: string[];
  productId?: string;
  productName?: string;
  status: 'draft' | 'published';
  isAutoGenerated: boolean;
  viewCount: number;
  helpfulCount: number;
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
}

export interface FAQAutoGenerateResult {
  question: string;
  suggestedAnswer: string;
  occurrence: number;
  confidence: number;
}